version: 0.1

phases:
  install:
    commands:
      - sudo apt-get update
      - sudo apt-get install apt-transport-https
      - sudo sh -c 'echo "deb [arch=amd64] https://apt-mo.trafficmanager.net/repos/dotnet-release/ trusty main" > /etc/apt/sources.list.d/dotnetdev.list'
      - sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 417A0893
      - sudo apt-get update
      - sudo apt-get install -y dotnet-dev-1.0.4
      - sudo apt-get update
  build:
    commands:
      - dotnet restore WebApp
      - dotnet publish -c release WebApp
  post_build:
    commands:
      - aws s3 cp WebApp/bin/release/netcoreapp1/publish/* s3://padnug/SpotAnalytics/WebApp
artifacts:
  files:
    - WebApp/serverless.template
    - WebApp/serverless-config.json
  discard-paths: yes
