version: 0.1

phases:
  install:
    commands:
      - sudo apt-get update
      - sudo apt-get install apt-transport-https
      - sudo sh -c 'echo "deb [arch=amd64] https://apt-mo.trafficmanager.net/repos/dotnet-release/ trusty main" > /etc/apt/sources.list.d/dotnetdev.list'
      - sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 417A0893
      - sudo apt-get update
      - sudo apt-get install -y dotnet-dev-1.0.4
      - sudo apt-get update
  build:
    commands:
      - dotnet restore WebApp
      - dotnet publish -c release WebApp
  post_build:
    commands:
      - cd WebApp/bin/release/netcoreapp1.0/publish/ && zip WebApp.zip -r *
      - find . ! -name 'WebApp/bin/release/netcoreapp1.0/publish/MyTest.zip' -type f -exec rm -f {} +
      - find . ! -name 'WebApp/bin/release/netcoreapp1.0/publish/MyTest.zip' -type d -exec rm -rf {} +
      - unzip WebApp/bin/release/netcoreapp1.0/publish/WebApp.zip
artifacts:
  files:
    - *
  discard-paths: yes
